version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_GITHUB_ACCESS_TOKEN }}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - github
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dependencies:
        patterns:
          - "*"
