openapi: 3.0.1
info:
  title: cucu
  description: Easy BDD web testing for local and CI, batteries included and extensible, with extremely descriptive reports
  x-cortex-tag: cucu
  x-cortex-type: service
  x-cortex-owners:
  - name: eng-automation
    type: group
    provider: OKTA
    description: Updated by eng-devprod
  x-cortex-git:
    github:
      alias: cortex
      repository: dominodatalab/cucu
  x-cortex-circle-ci:
    projects:
      - projectSlug: github/dominodatalab/cucu
