# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
---
version: 2.1

# workflows:
#   build-test-publish:
#     jobs:
#       - test:
#           name: test-chrome
#           browser: chrome
#       - test:
#           name: test-edge
#           browser: edge
#       - test:
#           name: test-firefox
#           browser: firefox

jobs:
  test:
    parameters:
      browser:
        type: string
        default: "chrome"
    docker:
      - image: cimg/python:3.11.7
      - image: selenium/standalone-<<parameters.browser>>:124.0
        environment:
          SE_NODE_MAX_SESSIONS: 12
          SE_NODE_SESSION_TIMEOUT: 300
          SCREEN_WIDTH: 1366
          SCREEN_HEIGHT: 768
    resource_class: xlarge
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install cucu dependencies
          command: |
            set +eo pipefail
            python -m virtualenv --upgrade-embed-wheels
            poetry install --no-ansi
      - run:
          name: install test dependencies
          command: |
            set +eo pipefail
            sudo apt-get update
            sudo apt-get install -y expect
      - run:
          name: wait_for_selenium
          # retry connection every 5s x 60 which is a total of 5 minutes
          command: curl --retry 60 --retry-delay 5 --retry-connrefused http://localhost:4444
      - run:
          name: run_functional_tests
          command: poetry run cucu run features --workers 6 --selenium-remote-url http://localhost:4444 --generate-report --junit junit_results --browser "<<parameters.browser>>"
          environment:
            COVERAGE_PROCESS_START: pyproject.toml  # set to config file
      - run:
          name: run unit tests
          command: poetry run coverage run -m pytest --junit-xml=results/unit-tests.xml
      - run:
          name: code_coverage_check
          command: |
            set +eo pipefail
            poetry run coverage combine .coverage.*
            poetry run coverage html
            poetry run coverage report
            poetry run coverage xml
            mv coverage.xml coverage-<<parameters.browser>>.xml
      - persist_to_workspace:
          root: .
          paths:
            - coverage-<<parameters.browser>>.xml
      - run:
          name: tar up results and reporting
          command: |
            tar cvfz results.tgz results
            tar cvfz report.tgz report
            tar cvfz junit_results.tgz junit_results
          when: always
      - store_artifacts:
          path: coverage-<<parameters.browser>>.xml
      - store_artifacts:
          path: results.tgz
      - store_artifacts:
          path: junit_results.tgz
      - store_artifacts:
          path: report.tgz
      - store_test_results:
          path: junit_results
