# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
---
version: 2.1

executors:
  unit-test-executor:
    docker:
      - image: python:3.11.5

  chrome-test-executor:
    docker:
      - image: python:3.11.5
      - image: selenium/standalone-chrome:114.0-chromedriver-114.0-20230614
        environment:
          SE_NODE_MAX_SESSIONS: 12
          SE_NODE_SESSION_TIMEOUT: 300
          SCREEN_WIDTH: 1366
          SCREEN_HEIGHT: 768
    resource_class: xlarge

  firefox-test-executor:
    docker:
      - image: python:3.11.5
      - image: selenium/standalone-firefox:114.0-geckodriver-0.33-20230614
        environment:
          SE_NODE_MAX_SESSIONS: 12
          SE_NODE_SESSION_TIMEOUT: 300
          SCREEN_WIDTH: 1366
          SCREEN_HEIGHT: 768
    resource_class: xlarge

  edge-test-executor:
    docker:
      - image: python:3.11.5
      - image: selenium/standalone-edge:114.0-edgedriver-114.0-20230614
        environment:
          SE_NODE_MAX_SESSIONS: 12
          SE_NODE_SESSION_TIMEOUT: 300
          SCREEN_WIDTH: 1366
          SCREEN_HEIGHT: 768
    resource_class: xlarge

commands:
  install_cucu_dependencies: &install_cucu_dependencies
    steps:
      - restore_cache:
          keys:
            - cucu-deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "poetry.lock" }}
      - run:
          name: install cucu dependencies
          no_output_timeout: 15m
          command: |
            set +eo pipefail
            pip install --upgrade pip
            pip install poetry
            poetry config installer.max-workers 10
            poetry config virtualenvs.in-project true
            poetry install --no-ansi
      - save_cache:
          paths:
            - ./.venv
          key: cucu-deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "poetry.lock" }}

  build_cucu_python_package: &build_cucu_python_package
    steps:
      - run:
          name: build the cucu python package
          command: poetry build

jobs:
  pre-commit:
    resource_class: medium
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            set +eo pipefail
            pip install --upgrade pip
            pip install pre-commit
            pre-commit install-hooks
      - install_cucu_dependencies
      - run:
          name: run pre-commit validations
          command: pre-commit run --show-diff-on-failure --from-ref origin/HEAD --to-ref HEAD

  build-and-install:
    resource_class: small
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - install_cucu_dependencies
      - build_cucu_python_package
      - run:
          name: install cucu globally
          command: pip install dist/cucu-*.tar.gz

  test:
    parameters:
      browser:
        type: string
        default: "chrome"
    executor: << parameters.browser >>-test-executor
    steps:
      - checkout
      - install_cucu_dependencies
      - run:
          name: install test dependencies
          command: |
            set +eo pipefail
            apt-get update
            apt-get install -y expect
      - setup_remote_docker:
          version: 20.10.14
      - run:
          # retry connection every 5s x 60 which is a total of 5 minutes
          command: curl --retry 60 --retry-delay 5 --retry-connrefused http://localhost:4444
      - run:
          command: poetry run cucu run features --workers 6 --selenium-remote-url http://localhost:4444 --generate-report --junit junit_results --browser "<< parameters.browser >>"
          environment:
            COVERAGE_PROCESS_START: pyproject.toml  # set to config file
      - run:
          name: run unit tests
          command: poetry run coverage run -m pytest --junit-xml=results/unit-tests.xml
      - run:
          command: |
            set +eo pipefail
            poetry run coverage combine .coverage.*
            poetry run coverage html
            poetry run coverage report --fail-under=70
      - run:
          name: tar up results and reporting
          command: |
            tar cvfz results.tgz results
            tar cvfz report.tgz report
            tar cvfz junit_results.tgz junit_results
          when: always
      - store_artifacts:
          path: results.tgz
      - store_artifacts:
          path: junit_results.tgz
      - store_artifacts:
          path: report.tgz
      - store_test_results:
          path: junit_results

  publish:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - install_cucu_dependencies
      - build_cucu_python_package
      - run:
          name: Publish to private PyPI repository
          command: |
            set +eo pipefail
            poetry config repositories.private ${PUBLISH_REPOSITORY}
            poetry config http-basic.private ${PUBLISH_USERNAME} ${PUBLISH_PASSWORD}
            poetry publish -r private

workflows:
  build-test-publish:
    jobs:
      - pre-commit
      - build-and-install:
          requires:
            - pre-commit
      - test:
          name: test-chrome
          browser: chrome
          requires:
            - pre-commit
      - test:
          name: test-edge
          browser: edge
          requires:
            - pre-commit
      - test:
          name: test-firefox
          browser: firefox
          requires:
            - pre-commit
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+/
