name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit poetry
        pre-commit install-hooks
    - name: install cucu dependencies
      run: |
        python -m virtualenv --upgrade-embed-wheels
        poetry install --no-ansi
    - name: build the cucu python package
      run: poetry build
    - name: install cucu globally
      run: pip install dist/cucu-*.tar.gz
    - name: run pre-commit validations
      run: pre-commit run --show-diff-on-failure --from-ref origin/HEAD --to-ref HEAD
