name: publish-production
# publish to pypi.org on merge to default branch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_publish_test]

jobs:
  publish-production-main:
    environment: cucu-publish-production  # match name in www.PyPI.org OIDC
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for connection to pypi OIDC
      contents: read  # For non-public repo
    steps:
      - name: checkout main
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: main
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          enable-cache: true
      - name: Install cucu with Python 3.12
        run: |
          uv sync -p 3.12
      - name: build package
        run: |
          uv build
      - name: publish to pypi.org
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
